[
    {
        "saleprice": "0",
        "linktext": "try it",
        "header": "<b> location 1 <\/b>",
        "carousel": "true",
        "tube": "youtube",
        "unitprice": "3",
        "carousel_caption": "",
        "showvideo": "false",
        "discontinued": "false",
        "expecteddate": "1970-01-01T00:00:00.000Z",
        "reorderlevel": "1",
        "faux": "false",
        "unitsonorder": "1",
        "shortdesc": "",
        "link": "",
        "description": "My location is HAL Bangalore",
        "notes": "",
        "unitsinstock": "1",
        "sortorder": "1",
        "videoid": "",
        "productid": "0B4MinpbTTsM-QTBlUTVFY2JWb00",
        "imagename": "https:\/\/drive.google.com\/thumbnail?authuser=0&id=0B4MinpbTTsM-QTBlUTVFY2JWb00",
        "storeid": "0B4MinpbTTsM-N1NVWUNFQ1dZdEk",
        "categoryname": "calender",
        "productname": "location1.jpg",
        "imageurl": "",
        "sku": "0B4MinpbTTsM-QTBlUTVFY2JWb00"
    },
    {
        "linktext": "try it",
        "saleprice": "0",
        "header": "<b> location 2 <\/b>",
        "carousel": "true",
        "tube": "youtube",
        "unitprice": "10",
        "carousel_caption": "",
        "showvideo": "false",
        "discontinued": "false",
        "expecteddate": "1970-01-01T00:00:00.000Z",
        "reorderlevel": "1",
        "faux": "false",
        "shortdesc": "",
        "unitsonorder": "1",
        "link": "",
        "notes": "",
        "unitsinstock": "1",
        "description": "location 2",
        "sortorder": "1",
        "videoid": "",
        "productid": "0B4MinpbTTsM-TVZIWHBrU3F4ZG8",
        "imagename": "https:\/\/drive.google.com\/thumbnail?authuser=0&id=0B4MinpbTTsM-TVZIWHBrU3F4ZG8",
        "storeid": "0B4MinpbTTsM-N1NVWUNFQ1dZdEk",
        "categoryname": "calender",
        "productname": "location2.jpg",
        "imageurl": "",
        "sku": "0B4MinpbTTsM-TVZIWHBrU3F4ZG8"
    },
    {
        "saleprice": "0",
        "linktext": "Fruit Chart (Apples, Peard, Quinces, Medlars) Link Text",
        "header": "<b> 14- FRUIT CHART 01.jpg <b>",
        "carousel": "1",
        "tube": "youtube",
        "unitprice": "0",
        "carousel_caption": "",
        "showvideo": "false",
        "discontinued": "false",
        "expecteddate": "1970-01-01T00:00:00.000Z",
        "reorderlevel": "1",
        "faux": "",
        "shortdesc": "Fruit Chart (Apples, Peard, Quinces, Medlars) Short Desc",
        "unitsonorder": "1",
        "link": "",
        "notes": "",
        "unitsinstock": "1",
        "description": "Fruit Chart (Apples, Peard, Quinces, Medlars) Desc",
        "videoid": "",
        "sortorder": "1",
        "productid": "0B4MinpbTTsM-SUdkUmd3Vllkd2c",
        "imagename": "https:\/\/drive.google.com\/thumbnail?authuser=0&id=0B4MinpbTTsM-SUdkUmd3Vllkd2c",
        "storeid": "0B4MinpbTTsM-WUtwRlE0Zkg2WTQ",
        "categoryname": "chart",
        "productname": "14- FRUIT CHART 01.jpg",
        "imageurl": "",
        "sku": "0B4MinpbTTsM-SUdkUmd3Vllkd2c"
    },
    {
        "saleprice": "2",
        "linktext": "try it",
        "header": "<b> Print me <\/b>",
        "carousel": "true",
        "tube": "youtube",
        "unitprice": "1",
        "carousel_caption": "",
        "showvideo": "false",
        "discontinued": "false",
        "expecteddate": "1970-01-01T00:00:00.000Z",
        "reorderlevel": "1",
        "faux": "false",
        "unitsonorder": "1",
        "shortdesc": "",
        "link": "",
        "description": "Very good product to purchase",
        "notes": "good notes",
        "unitsinstock": "1",
        "sortorder": "1",
        "videoid": "",
        "productid": "0B4MinpbTTsM-UWVhekNyLWliOUk",
        "imagename": "https:\/\/drive.google.com\/thumbnail?authuser=0&id=0B4MinpbTTsM-UWVhekNyLWliOUk",
        "storeid": "0B4MinpbTTsM-WUtwRlE0Zkg2WTQ",
        "categoryname": "chart",
        "productname": "print.png",
        "imageurl": "",
        "sku": "0B4MinpbTTsM-UWVhekNyLWliOUk"
    },
    {
        "linktext": "try it",
        "saleprice": "0",
        "header": "<b> header <\/b>",
        "carousel": "true",
        "unitprice": "0",
        "tube": "youtube",
        "carousel_caption": "",
        "showvideo": "false",
        "discontinued": "false",
        "expecteddate": "1970-01-01T00:00:00.000Z",
        "reorderlevel": "1",
        "faux": "false",
        "shortdesc": "",
        "unitsonorder": "1",
        "link": "",
        "notes": "",
        "unitsinstock": "1",
        "description": "Ria",
        "sortorder": "1",
        "videoid": "",
        "productid": "0B4MinpbTTsM-dnkzNWR3V2FMTUE",
        "imagename": "https:\/\/drive.google.com\/thumbnail?authuser=0&id=0B4MinpbTTsM-dnkzNWR3V2FMTUE",
        "storeid": "0B4MinpbTTsM-WUtwRlE0Zkg2WTQ",
        "categoryname": "chart",
        "productname": "ria.jpg",
        "imageurl": "",
        "sku": "0B4MinpbTTsM-dnkzNWR3V2FMTUE"
    }
]